import { GoogleGenAI } from "@google/genai";
import { MODEL_NAME } from "../constants";

// Helper to remove data URL prefix for API calls if needed, 
// though @google/genai often takes base64 data directly.
const extractBase64 = (dataUrl: string): string => {
  return dataUrl.split(',')[1];
};

const getMimeType = (dataUrl: string): string => {
  const match = dataUrl.match(/^data:(.+);base64,/);
  return match ? match[1] : 'image/jpeg';
};

export const generateMarketingImage = async (
  imageBase64: string,
  prompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing. Please set the API_KEY environment variable.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const base64Data = extractBase64(imageBase64);
  const mimeType = getMimeType(imageBase64);

  // Construct the prompt
  // We want to transform the image.
  const finalPrompt = `
    Transform this product photo into a stunning marketing image.
    The input image contains the product. Keep the product's appearance, shape, and label details exactly as they are.
    
    ${prompt}
    
    Ensure the lighting on the product matches the new background. 
    High resolution, 4k, photorealistic.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: finalPrompt,
          },
        ],
      },
    });

    // Parse response for image
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
